### ISSUE TITLE
Please, don't change your nickname so often!

### ISSUE THREAD

**Issue by L11R** [s32x/ovrstat#36]
@s32x, if you so like it, let's use gopkg.in with stable package link. Otherwise I have to change my sources codes everytime.

**Comment by s32x** [comment]
Sorry! I won't be changing my username again. From now on the import url will be `s32x.com/ovrstat/ovrstat`

**Comment by L11R** [comment]
Thanks for understanding and link! Do you plan do maintain this domain reasonably long?

**Comment by s32x** [comment]
Absolutely. I plan on keeping the custom domain set up and running indefinitely. Hopefully, this shows I'm a little more committed to the username :)

**Comment by L11R** [comment]
@s32x a little bit offtopic, but me to, tbh, I also had previously `Lord-Protector`, but a like it short like l18n.
Also had short domain lord.sh for such projects and links :)

**Comment by s32x** [comment]
OH Yeah me too! Shorter feels more professional. s32x is a little more mature than starboy as well haha
