### ISSUE TITLE
Failed to perform lookup

### ISSUE THREAD

**Issue by SlimShadyIAm** [s32x/ovrstat#42]
Hello,
I had no trouble setting up the API the first time I used it. Today I started a new server and tried setting it up again and the response I receive to all requests is "Failed to perform lookup:". The homepage works fine, just lookups don't. 

I'm on Ubuntu 18.04 running the latest Docker CE, tried both golang-go and the snap version of Go.

**Comment by SlimShadyIAm** [comment]
I found a fork of your project on Docker Hub which works without issues, but it's based on an older version of your project and has its own set of bugs. https://hub.docker.com/r/naddison/ovrstat.

Could you maybe have broken something with your update to your image 11 days ago?

**Comment by naddison** [comment]
@SlimShadyIAm I wouldn't use my image, its old. I am experiencing the same problem you are with the "Failed to perform lookup"

**Comment by naddison** [comment]
I can't even get the tests to work when building the image locally. I am *really* green at golang, and the change in modules is looping me.

**Comment by naddison** [comment]
Reverting to https://github.com/s32x/ovrstat/commit/9961bcc460f0492f7a468b398cf6d415c4d85ad8 got me a working image locally.

**Comment by SlimShadyIAm** [comment]
> @SlimShadyIAm I wouldn't use my image, its old. I am experiencing the same problem you are with the "Failed to perform lookup"

Thanks for confirming the issue. I was only using your image because I was migrating servers and needed a temporary working solution. For my project I'm now using a scraper I threw together myself quickly.

> Reverting to [9961bcc](https://github.com/s32x/ovrstat/commit/9961bcc460f0492f7a468b398cf6d415c4d85ad8) got me a working image locally.

I suppose this information will be useful to others, seems the developer is currently inactive. Thanks!

**Comment by s32x** [comment]
Hey sorry, this is a really old bug. I've been very busy since this bug came up but have just gotten around to fixing it. Let me know if you're still having troubles. Feel free to re-open if the problem isn't fully fixed
