### ISSUE TITLE
Rating and endorsement are not showing properly

### ISSUE THREAD

**Issue by Eleiber** [s32x/ovrstat#44]
After the rating update, the rating and the endorsement appears as 0 with any user when you search for it

![image](https://user-images.githubusercontent.com/13054092/63106311-8fa8bd00-bf50-11e9-9f1b-3518b752cf17.png)

**Comment by seilem** [comment]
Already fixed [here](https://github.com/s32x/ovrstat/commit/4c14ad97d0ea9310e18e384e0ade0824db6da146).

**Comment by Eleiber** [comment]
Fine, I see, but why does the API Endpoint keep returning me 0 as value?
![image](https://user-images.githubusercontent.com/13054092/63122170-11f6a880-bf74-11e9-97d5-7bc91b9f0a7b.png)

**Comment by seilem** [comment]
Oops, I forgot about site endpoint. It will be updated [soon](https://github.com/s32x/ovrstat/pull/43#issuecomment-521726722).

**Comment by s32x** [comment]
Just did the deploy. The output looks awesome. Thanks again @seilem. Should be fixed - if not please feel free to re-open
