### ISSUE TITLE
Newest update changes website

### ISSUE THREAD

**Issue by OzairP** [s32x/ovrstat#45]
I don't know Go but I believe the service is now failing and returning 404's for every player since a new update to the website.

The falsey error is here: https://github.com/s32x/ovrstat/blob/master/ovrstat/player_stats.go#L95

It looks like you were using an internal http api, but now that does not exist and the data is just served with the HTML meaning actual web scraping has to be done.

**Comment by tystuyfzand** [comment]
This update did indeed break it, but it looks like we can still use the search page for the exact same data. I'm working on an update using the following URL.

https://playoverwatch.com/en-us/search/account-by-name/Viz%231213

**Comment by OzairP** [comment]
Thanks!
