### ISSUE TITLE
Proposal to keep package up-to-date

### ISSUE THREAD

**Issue by tystuyfzand** [s32x/ovrstat#49]
With how much Blizzard likes to break this, I've seen a few names pop up that maintain the library pretty well.

@seilem, @L11R, and I for sure have a few commits resolving some issues, and I sure wouldn't mind contributing to keep it up to date as often as possible, so I'd like to propose the possibility of making it an organization or having a few select maintainers able to keep it up to date.

Not sure how this would work, though it'd be cool to see. I've also considered a modification that would automatically find the appropriate elements based off certain keys/structures, keeping them cached until a known profile fails.

**Comment by s32x** [comment]
Creating an entire organization for a single project is a little overkill in my opinion. The same can easily be accomplished by adding collaborators to this repository as it is. I also don't like the idea of allowing merges without seeing it myself. I'm always open to pull requests and regularly approve them pretty quickly.

I really appreciate the input though and if you have a fix absolutely feel free to create a pull request. Any big modifications or intelligent logic is sort of out of the scope of this project however and I'd encourage you to create a fork.
