### ISSUE TITLE
Please update overstat.com to use the latest version

### ISSUE THREAD

**Issue by gk0r** [s32x/ovrstat#51]
Hi 

Please update the deployment on `https://ovrstat.com/` to the latest version of this library. I noticed that it's not processing the competitive ratings anymore.

Thanks

**Comment by s32x** [comment]
Done. Sorry about that. Let me know if it's still acting up.

**Comment by gk0r** [comment]
Is there a particular reason why its returning `"ratings": null` for entries that should have legitimate ratings displayed? For example: `https://playoverwatch.com/en-gb/career/pc/CatsGotAJob-1946` should  return `2789`, `2600` and `3400` for `Tank`, `Damage` and `Support` respectively.

I was expecting the latest version to display these correctly, but that doesn't seem to be the case? Am I missing something?
